/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-21 14:35:59
*/

package com.silvera.UserService.repository;

import com.silvera.UserService.domain.model.AuthRequest;
import org.springframework.data.mongodb.repository.MongoRepository;


public interface AuthRequestRepository extends MongoRepository<AuthRequest, java.lang.String> {
  // CRUD operations are included in MongoRepository interface

}