/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-21 19:49:12
*/

package com.silvera.UserService.repository;

import com.silvera.UserService.domain.model.User;
import org.springframework.data.mongodb.repository.MongoRepository;

import java.util.Optional;


public interface UserRepository extends MongoRepository<User, java.lang.String> {
    Optional<User> findByUsername(String username);
    // CRUD operations are included in MongoRepository interface

}