/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-21 16:42:57
*/

package com.silvera.SciPaperService.domain.model;

import org.springframework.data.annotation.Id;
import javax.validation.constraints.*;
public class PublishPaperInfo {

    
    
    
    @Id
    
    @NotBlank(message="Field 'id' cannot be empty!")
    private java.lang.String id;
    
    private java.lang.String username;


    
    public java.lang.String getId() {
        return this.id;
    }

    public void setId(java.lang.String id) {
        this.id = id;
    }
    
    public java.lang.String getUsername() {
        return this.username;
    }

    public void setUsername(java.lang.String username) {
        this.username = username;
    }
    

    

}