/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-21 14:35:59
*/

package com.silvera.LibraryService.controller;

import java.util.Collection;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cloud.context.config.annotation.RefreshScope;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.ResponseBody;
import com.silvera.LibraryService.service.base.*;
import com.silvera.LibraryService.domain.model.*;
import com.silvera.LibraryService.messages.*;
import org.springframework.web.bind.annotation.*;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.kafka.core.KafkaTemplate;
import javax.validation.Valid;


@RefreshScope
@RestController
public class LibraryServiceController {

    @Autowired
    ILibraryServiceService libraryServiceService;

    // Auto-generated CRUD methods
    

    //
    // Public functions
    //
    
    

    @GetMapping(value="listallpapers")


    public java.util.List<PublishedPaper> listAllPapers(){
        
        return libraryServiceService.listAllPapers();

    }
    

    //
    // Message consumers
    //
    
    
    @KafkaListener(
        topics = { "PUBLISH_PAPPER" },
        groupId = "LibraryService",
        containerFactory = "papermsggroupPublishPaperKafkaListenerContainerFactory"
    )
    public void publishPaper(com.silvera.LibraryService.messages.papermsggroup.PublishPaper message){
        libraryServiceService.publishPaper(message);
    }
    
    
}