/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-21 19:49:12
*/

package com.silvera.SciPaperService.controller;

import java.util.Collection;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cloud.context.config.annotation.RefreshScope;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.ResponseBody;
import com.silvera.SciPaperService.service.base.*;
import com.silvera.SciPaperService.domain.model.*;
import com.silvera.SciPaperService.messages.*;
import org.springframework.web.bind.annotation.*;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.kafka.core.KafkaTemplate;
import javax.validation.Valid;


@RefreshScope
@RestController
public class SciPaperServiceController {

    @Autowired
    ISciPaperServiceService sciPaperServiceService;

    // Auto-generated CRUD methods
    
    
    
    @RequestMapping(value="/scipaper", method=RequestMethod.POST)
    @ResponseBody
    public SciPaper createSciPaper(@Valid @RequestBody SciPaper scipaper){
        return sciPaperServiceService.createSciPaper(scipaper);
    }
    
    
    
    
    

    //
    // Public functions
    //
    
    

    @PostMapping(value = "publish")


    public java.lang.Boolean publish(@RequestBody PublishPaperInfo publishPaperInfo){
        
        return sciPaperServiceService.publish(publishPaperInfo);

    }
    
    

    @GetMapping(value="/all")


    public java.util.List<SciPaper> showAllPapers(){
        
        return sciPaperServiceService.showAllPapers();

    }
    

    //
    // Message consumers
    //
    
}