/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-21 11:29:00
*/

package com.silvera.SciPaperService.controller;

import java.util.Collection;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cloud.context.config.annotation.RefreshScope;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.ResponseBody;
import javax.validation.Valid;

import com.silvera.SciPaperService.service.base.ISciPaperServiceService;
import com.silvera.SciPaperService.domain.model.*;



@RefreshScope
@RestController
public class SciPaperServiceController {

    @Autowired
    ISciPaperServiceService sciPaperServiceService;

    // Auto-generated CRUD methods
    



    
        
    

    @PostMapping(value = "publish")


    @ResponseBody
    public java.lang.Boolean publish() {
        
        return sciPaperServiceService.publish();

    }
    

}