/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-21 11:29:00
*/

package com.silvera.LibraryService.domain.model;

import org.springframework.data.annotation.Id;
import javax.validation.constraints.*;
public class PublishedPaper {

    
    @Id
    private String id;
    
    
    private java.lang.String ID;
    
    private java.lang.String title;
    
    private java.lang.String author;


    
    public java.lang.String getID() {
        return this.ID;
    }

    public void setID(java.lang.String ID) {
        this.ID = ID;
    }
    
    public java.lang.String getTitle() {
        return this.title;
    }

    public void setTitle(java.lang.String title) {
        this.title = title;
    }
    
    public java.lang.String getAuthor() {
        return this.author;
    }

    public void setAuthor(java.lang.String author) {
        this.author = author;
    }
    

    
    public String getId(){
        return this.id;
    }
    
}