/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-21 14:35:59
*/

package com.silvera.SciPaperService.messages.papermsggroup;

import com.silvera.SciPaperService.messages.Message;

public class PublishPaper extends Message {

    
    private java.lang.String id;
    private java.lang.String title;
    private java.lang.String author;


    public PublishPaper(){
        this.name = "PaperMsgGroup.PublishPaper";
    }
    public java.lang.String getId() {
        return this.id;
    }

    public void setId(java.lang.String id) {
        this.id = id;
    }
    
    public java.lang.String getTitle() {
        return this.title;
    }

    public void setTitle(java.lang.String title) {
        this.title = title;
    }
    
    public java.lang.String getAuthor() {
        return this.author;
    }

    public void setAuthor(java.lang.String author) {
        this.author = author;
    }
    

}