/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-21 14:35:59
*/

package com.silvera.LibraryService.repository;

import com.silvera.LibraryService.domain.model.PublishedPaper;
import org.springframework.data.mongodb.repository.MongoRepository;


public interface PublishedPaperRepository extends MongoRepository<PublishedPaper, java.lang.String> {
  // CRUD operations are included in MongoRepository interface

}