/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-21 19:49:12
*/

package com.silvera.SciPaperService.repository;

import com.silvera.SciPaperService.domain.model.PublishPaperInfo;
import org.springframework.data.mongodb.repository.MongoRepository;


public interface PublishPaperInfoRepository extends MongoRepository<PublishPaperInfo, java.lang.String> {
  // CRUD operations are included in MongoRepository interface

}