/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-21 19:30:36
*/

package com.silvera.UserService.domain.model;

import org.springframework.data.annotation.Id;
import javax.validation.constraints.*;
public class AuthResponse {

    
    @Id
    private String id;
    
    
    private java.lang.Boolean loggedIn;


    
    public java.lang.Boolean getLoggedIn() {
        return this.loggedIn;
    }

    public void setLoggedIn(java.lang.Boolean loggedIn) {
        this.loggedIn = loggedIn;
    }
    

    
    public String getId(){
        return this.id;
    }
    
}