/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-21 11:29:00
*/

package com.silvera.UserService.domain.model;

import org.springframework.data.annotation.Id;
import javax.validation.constraints.*;
public class AuthResponse {

    
    
    
    @Id
    
    @NotBlank(message="Field 'username' cannot be empty!")
    private java.lang.String username;
    
    private java.lang.String jwt;


    
    public java.lang.String getUsername() {
        return this.username;
    }

    public void setUsername(java.lang.String username) {
        this.username = username;
    }
    
    public java.lang.String getJwt() {
        return this.jwt;
    }

    public void setJwt(java.lang.String jwt) {
        this.jwt = jwt;
    }
    

    
    public java.lang.String getId(){
        return this.username;
    }
    
}