/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-21 11:29:00
*/

package com.silvera.SciPaperService.service.base;

import com.silvera.SciPaperService.domain.model.*;


public interface ISciPaperServiceService {

    // Auto-generated CRUD methods
    


    
     
    
    public java.lang.Boolean publish() ;
    

}