/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-21 16:42:57
*/

package com.silvera.SciPaperService.service.base;

import org.springframework.stereotype.Service;
import com.silvera.SciPaperService.domain.model.*;
import com.silvera.SciPaperService.messages.*;
import org.springframework.beans.factory.annotation.Autowired;


public interface ISciPaperServiceService {

    // Auto-generated CRUD methods
    
    
    
    public SciPaper createSciPaper(SciPaper scipaper);
    
    
    public SciPaper updateSciPaper(java.lang.String id, SciPaper scipaperUpdate);
    
    
    public SciPaper readSciPaper(java.lang.String id);
    
    
    public void deleteSciPaper(java.lang.String id);
    
    

    
    public java.lang.Boolean publish(PublishPaperInfo publishPaperInfo);
    

    

}