/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-21 11:29:00
*/

package com.silvera.LibraryService.service.base;

import com.silvera.LibraryService.domain.model.*;


public interface ILibraryServiceService {

    // Auto-generated CRUD methods
    


    
     
    
    public java.util.List<PublishedPaper> listAllPapers() ;
    

}