/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-21 19:49:12
*/

package com.silvera.LibraryService.service.base;

import org.springframework.stereotype.Service;
import com.silvera.LibraryService.domain.model.*;
import com.silvera.LibraryService.messages.*;
import org.springframework.beans.factory.annotation.Autowired;


public interface ILibraryServiceService {

    // Auto-generated CRUD methods
    

    
    public java.util.List<PublishedPaper> listAllPapers();
    

    
    
    public void publishPaper(com.silvera.LibraryService.messages.papermsggroup.PublishPaper message);
    
    

}