/**
    Use this file to implement business logic. This file will be preserved
    during next compilations.

    Generated by: silvera
    Date: 2022-05-21 14:35:59
*/

package com.silvera.SciPaperService.service.impl;

import java.util.Optional;

import com.silvera.SciPaperService.messages.papermsggroup.PublishPaper;
import org.springframework.stereotype.Service;
import com.silvera.SciPaperService.domain.model.*;
import com.silvera.SciPaperService.service.base.*;
import com.silvera.SciPaperService.repository.*;
import com.silvera.SciPaperService.messages.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.kafka.core.KafkaTemplate;


@Service
public class SciPaperServiceService implements ISciPaperServiceService {

    
    
    @Autowired
    SciPaperRepository scipaperRepository;
    

    

    @Autowired
    KafkaTemplate<String, com.silvera.SciPaperService.messages.papermsggroup.PublishPaper> papermsggroupPublishPaperKafkaTemplate;
    

    // Auto-generated CRUD methods
    
    @Override
    public SciPaper createSciPaper(SciPaper scipaper){
        scipaperRepository.save(scipaper);

        

        Optional<SciPaper> opt = scipaperRepository.findById(scipaper.getId());
        return opt.orElse(null);
    }
    
    
    @Override
    public SciPaper updateSciPaper(java.lang.String id, SciPaper scipaperUpdate){
        Optional<SciPaper> opt = scipaperRepository.findById(id);
        SciPaper entity = opt.orElseThrow(IllegalArgumentException::new);
        scipaperRepository.save(scipaperUpdate);

        

        return scipaperUpdate;
    }
    
    
    @Override
    public SciPaper readSciPaper(java.lang.String id){
        Optional<SciPaper> opt = scipaperRepository.findById(id);
        return opt.orElseThrow(IllegalArgumentException::new);
    }
    
    
    @Override
    public void deleteSciPaper(java.lang.String id){
        Optional<SciPaper> opt = scipaperRepository.findById(id);
        SciPaper entity = opt.orElseThrow(IllegalArgumentException::new);
        scipaperRepository.delete(entity);

        
    }
    
    


    
    @Override
    public SciPaper createPaper(SciPaper sciPaper){
        /*
            TODO: Implement this function!!!
        */
        // Uncomment to publish the message
        //com.silvera.SciPaperService.messages.papermsggroup.PublishPaper msg = new com.silvera.SciPaperService.messages.papermsggroup.PublishPaper();
        // Here set values to the message attributes:
        // ------------------------------------------

        // ------------------------------------------
        //papermsggroupPublishPaperKafkaTemplate.send("PUBLISH_PAPPER", msg);
        

        throw new java.lang.UnsupportedOperationException("Not implemented yet.");
    }
    
    @Override
    public java.lang.Boolean publish(java.lang.String id, java.lang.String username){
        /*
            TODO: Implement this function!!!
        */

        PublishPaper msg = new PublishPaper();
        msg.setId(id);
        msg.setAuthor("Pera");
        msg.setTitle("Perina knjiga");

        papermsggroupPublishPaperKafkaTemplate.send("PUBLISH_PAPPER", msg);
        return true;
    }
    

    

}