/**
    Use this file to implement business logic. This file will be preserved
    during next compilations.

    Generated by: silvera
    Date: 2022-05-21 19:20:10
*/

package com.silvera.SciPaperService.service.impl;

import java.util.Optional;
import org.springframework.stereotype.Service;
import com.silvera.SciPaperService.domain.model.*;
import com.silvera.SciPaperService.service.base.*;
import com.silvera.SciPaperService.repository.*;
import com.silvera.SciPaperService.messages.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.kafka.core.KafkaTemplate;

import com.silvera.SciPaperService.service.dependencies.*;


@Service
public class SciPaperServiceService implements ISciPaperServiceService {

    
    
    @Autowired
    SciPaperRepository scipaperRepository;
    

    
    @Autowired
    UserServiceClient userServiceClient;
    

    @Autowired
    KafkaTemplate<String, com.silvera.SciPaperService.messages.papermsggroup.PublishPaper> papermsggroupPublishPaperKafkaTemplate;
    

    // Auto-generated CRUD methods
    
    @Override
    public SciPaper createSciPaper(SciPaper scipaper){
        if (userServiceClient.isLoggedIn(scipaper.getAuthor()).equals(Boolean.FALSE)){
            throw new IllegalArgumentException("User " + scipaper.getAuthor() + " is not logged in!");
        }
        scipaperRepository.save(scipaper);

        

        Optional<SciPaper> opt = scipaperRepository.findById(scipaper.getId());
        return opt.orElse(null);
    }



    @Override
    public java.lang.Boolean publish(PublishPaperInfo publishPaperInfo){

        if (userServiceClient.isLoggedIn(publishPaperInfo.getUsername()).equals(Boolean.FALSE)){
            throw new IllegalArgumentException("User " + publishPaperInfo.getUsername() + " is not logged in!");
        }


        String name = userServiceClient.getName(publishPaperInfo.getUsername());
        if (name.equals("")){
            throw new IllegalArgumentException("Service temporary unavailable");
        }

        // Uncomment to publish the message
        com.silvera.SciPaperService.messages.papermsggroup.PublishPaper msg = new com.silvera.SciPaperService.messages.papermsggroup.PublishPaper();
        // Here set values to the message attributes:
        // ------------------------------------------

        msg.setId(publishPaperInfo.getId());
        Optional<SciPaper> opt = scipaperRepository.findById(publishPaperInfo.getId());
        SciPaper entity = opt.orElseThrow(IllegalArgumentException::new);
        if(!entity.getAuthor().equals(publishPaperInfo.getUsername())){
            throw new IllegalArgumentException("You can only publish your own papers!");
        }
        msg.setTitle(entity.getTitle());
        msg.setAuthor(name);
        // ------------------------------------------
        papermsggroupPublishPaperKafkaTemplate.send("PUBLISH_PAPPER", msg);
        return true;
    }
    
    @Override
    public java.util.List<SciPaper> showAllPapers(){
        return scipaperRepository.findAll();
    }
    

    

}