/**
    Use this file to implement business logic. This file will be preserved
    during next compilations.

    Generated by: silvera
    Date: 2022-05-21 11:29:00
*/

package com.silvera.SciPaperService.service.impl;

import java.util.Optional;
import org.springframework.stereotype.Service;
import com.silvera.SciPaperService.domain.model.*;
import com.silvera.SciPaperService.repository.*;
import com.silvera.SciPaperService.service.base.*;

import org.springframework.beans.factory.annotation.Autowired;





@Service
public class SciPaperServiceService implements ISciPaperServiceService {

    

    

    public SciPaperServiceService(){
        super();
    }

    // Auto-generated CRUD methods
    

    
    
    
    @Override
    public java.lang.Boolean publish() {
        /*
            TODO: Implement this function!!!
        */
        throw new java.lang.UnsupportedOperationException("Not implemented yet.");
    }
    

}