/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-21 14:35:59
*/

package com.silvera.UserService.service.base;

import com.silvera.UserService.domain.model.*;


public interface IUserServiceService {

    // Auto-generated CRUD methods
    


    
     
    
    public AuthResponse authenticate(AuthRequest authRequest) ;
    
     
    
    public java.lang.String register(User user) ;
    
     
    
    public java.lang.Boolean isLoggedIn(java.lang.String jwt) ;
    
     
    
    public java.lang.String getName(java.lang.String jwt) ;
    

}