/**
    Use this file to implement business logic. This file will be preserved
    during next compilations.

    Generated by: silvera
    Date: 2022-05-21 14:35:59
*/

package com.silvera.LibraryService.service.impl;

import java.util.Optional;
import org.springframework.stereotype.Service;
import com.silvera.LibraryService.domain.model.*;
import com.silvera.LibraryService.service.base.*;
import com.silvera.LibraryService.repository.*;
import com.silvera.LibraryService.messages.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.kafka.core.KafkaTemplate;


@Service
public class LibraryServiceService implements ILibraryServiceService {

    

    

    

    // Auto-generated CRUD methods
    


    
    @Override
    public java.util.List<PublishedPaper> listAllPapers(){
        /*
            TODO: Implement this function!!!
        */
        

        throw new java.lang.UnsupportedOperationException("Not implemented yet.");
    }
    

    
    
    @Override
    public void publishPaper(com.silvera.LibraryService.messages.papermsggroup.PublishPaper message){
        /*
            TODO: Implement this function!!!
        */

        System.out.println(message.getTitle());


    }
    
    

}