/**
    Use this file to implement business logic. This file will be preserved
    during next compilations.

    Generated by: silvera
    Date: 2022-05-21 11:29:00
*/

package com.silvera.LibraryService.service.impl;

import java.util.Optional;
import org.springframework.stereotype.Service;
import com.silvera.LibraryService.domain.model.*;
import com.silvera.LibraryService.repository.*;
import com.silvera.LibraryService.service.base.*;

import org.springframework.beans.factory.annotation.Autowired;





@Service
public class LibraryServiceService implements ILibraryServiceService {

    

    

    public LibraryServiceService(){
        super();
    }

    // Auto-generated CRUD methods
    

    
    
    
    @Override
    public java.util.List<PublishedPaper> listAllPapers() {
        /*
            TODO: Implement this function!!!
        */
        throw new java.lang.UnsupportedOperationException("Not implemented yet.");
    }
    

}