/**
    Use this file to implement business logic. This file will be preserved
    during next compilations.

    Generated by: silvera
    Date: 2022-05-21 14:35:59
*/

package com.silvera.LibraryService.service.impl;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.silvera.LibraryService.domain.model.*;
import com.silvera.LibraryService.service.base.*;
import com.silvera.LibraryService.repository.*;


@Service
public class LibraryServiceService implements ILibraryServiceService {

    

    private final PublishedPaperRepository publishedPaperRepository;

    @Autowired
    public LibraryServiceService(PublishedPaperRepository publishedPaperRepository) {
        this.publishedPaperRepository = publishedPaperRepository;
    }


    // Auto-generated CRUD methods
    


    
    @Override
    public java.util.List<PublishedPaper> listAllPapers(){
        /*
            TODO: Implement this function!!!
        */
        

        return publishedPaperRepository.findAll();
    }
    

    
    
    @Override
    public void publishPaper(com.silvera.LibraryService.messages.papermsggroup.PublishPaper message){

        PublishedPaper paper = new PublishedPaper();
        paper.setId(message.getId());
        paper.setAuthor(message.getAuthor());
        paper.setTitle(message.getTitle());

        publishedPaperRepository.save(paper);
    }
    
    

}