/**
    Use this file to implement business logic. This file will be preserved
    during next compilations.

    Generated by: silvera
    Date: 2022-05-21 14:35:59
*/

package com.silvera.UserService.service.impl;

import java.util.Optional;
import org.springframework.stereotype.Service;
import com.silvera.UserService.domain.model.*;
import com.silvera.UserService.repository.*;
import com.silvera.UserService.service.base.*;

import org.springframework.beans.factory.annotation.Autowired;





@Service
public class UserServiceService implements IUserServiceService {

    

    

    public UserServiceService(){
        super();
    }

    // Auto-generated CRUD methods
    

    
    
    
    @Override
    public AuthResponse authenticate(AuthRequest authRequest) {
        /*
            TODO: Implement this function!!!
        */
        throw new java.lang.UnsupportedOperationException("Not implemented yet.");
    }
    
    
    
    @Override
    public java.lang.String register(User user) {
        /*
            TODO: Implement this function!!!
        */
        throw new java.lang.UnsupportedOperationException("Not implemented yet.");
    }
    
    
    
    @Override
    public java.lang.Boolean isLoggedIn(java.lang.String jwt) {
        /*
            TODO: Implement this function!!!
        */
        throw new java.lang.UnsupportedOperationException("Not implemented yet.");
    }
    
    
    
    @Override
    public java.lang.String getName(java.lang.String jwt) {
        /*
            TODO: Implement this function!!!
        */
        throw new java.lang.UnsupportedOperationException("Not implemented yet.");
    }
    

}